vim.pack.add({ "https://github.com/sindrets/diffview.nvim" })
-- local actions = require("diffview.actions")
require("diffview").setup()
vim.keymap.set("n", "<leader>mt", ":DiffviewOpen ", { desc = "open diff view" })
vim.keymap.set("n", "<leader>mf", ":DiffviewFileHistory ", { desc = "open diff view for single file" })
vim.keymap.set("n", "<leader>mk", ":DiffviewClose<CR>", { desc = "close diff view", silent = true })
