vim.pack.add({ "https://github.com/folke/flash.nvim" })

vim.keymap.set("n", "s", function()
	require("flash").jump()
end, { noremap = true, silent = true })
vim.keymap.set("x", "s", function()
	require("flash").jump()
end, { noremap = true, silent = true })
vim.keymap.set("o", "s", function()
	require("flash").jump()
end, { noremap = true, silent = true })
vim.keymap.set("o", "r", function()
	require("flash").remote()
end, { noremap = true, silent = true })
vim.keymap.set("n", "S", function()
	require("flash").treesitter()
end, { silent = true })
vim.keymap.set("o", "S", function()
	require("flash").treesitter()
end, { silent = true })
-- vim.keymap.set("x", "S", function()
-- 	require("flash").treesitter()
-- end, { silent = true })

vim.api.nvim_set_hl(0, "FlashLabel", { fg = "#000000", bg = "#aaf800" })
