vim.pack.add({'https://github.com/tpope/vim-fugitive'})
vim.keymap.set('n', "<leader>gg",":Git ", {desc = "open git", noremap = true, silent = true })
vim.keymap.set('n', "<leader>gc",":Git commit<CR>", {desc = "git commit", noremap = true, silent = true, })
vim.keymap.set('n', "<leader>gp",":Git push<CR>", {desc = "git push", silent = true })
vim.keymap.set('n', "<leader>bl",":Git blame<CR>", {desc = "git blame", noremap = true, silent = true })
