require("indent_blankline").setup {
  char = "▏",
  buftype_exclude = {"terminal", "nofile"},
  filetype_exclude = {"help", "dashboard", "NvimTree", "Outline", "TelescopePrompt"},
  use_treesitter = true,
  show_current_context = true,
  context_patterns = {
    "class",
    "function",
    "method",
    "^if",
    "^while",
    "^for",
    "^object",
    "^table",
    "block",
    "arguments",
    "if_statement",
    "else_clause",
    "jsx_element",
    "jsx_self_closing_element",
    "try_statement",
    "catch_clause",
    "import_statement",
    "operation_type",
  },
  context_highlight_list = {
    "IndentBlanklineContext",
    "IndentBlanklineContext1",
    "IndentBlanklineContext2",
    "IndentBlanklineContext3",
    "IndentBlanklineContext4",
    "IndentBlanklineContext5",
    "IndentBlanklineContext6",
  },
  show_trailing_blankline_indent = false,
  show_first_indent_level = false,
  space_char_blankline = " ",
  space_char_blankline_highlight = "IndentBlankline",
}
